--
SELECT T2.Rollno,T1.StuName,T2.SubID,T2.Examtimes,T2.Marks
FROM STUDENT AS T1, EXAMMARK AS T2 
WHERE T1.Rollno = T2.Rollno
--
SELECT T2.Rollno,T1.SubID,T1.SubName,T2.SubID,T2.Examtimes,T2.Marks
FROM SUBJECT AS T1, EXAMMARK AS T2 
WHERE T1.SubID = T2.SubID
--
SELECT T1.Rollno,T2.StuName,T1.SubID,T3.SubName,T1.Examtimes,T1.Marks
FROM EXAMMARK AS T1, STUDENT AS T2, [SUBJECT] AS T3 
WHERE T1.Rollno=T2.Rollno AND T1.SubID = T3.SubID
-- 
INSERT INTO STUDENT VALUES('SV05','Hoang Thuy Phuong','Female','So 1- Ly Tu Trong Can Tho');
WITH STUDENTTEMP(Rollno,StuName,Gender,Address)
AS (SELECT * FROM STUDENT)
SELECT * FROM STUDENTTEMP
--
SELECT * FROM STUDENT
--
SELECT * FROM STUDENT
WHERE Rollno IN (SELECT Rollno FROM EXAMMARK)
--
SELECT * FROM STUDENT
WHERE Rollno NOT IN (SELECT Rollno FROM EXAMMARK)
--
SELECT * FROM STUDENT
WHERE Rollno NOT IN (SELECT Rollno FROM EXAMMARK T1 WHERE SubID='HDJ')
--
SELECT T1.Rollno,T2.StuName,T2.Gender,T2.Address,T1.SubID,T1.Marks
FROM EXAMMARK AS T1, STUDENT T2
WHERE (Marks>=80) AND T1.Rollno = T2.Rollno
--
SELECT T1.Rollno,T2.StuName,T2.Gender,T2.Address,T1.SubID,T1.Marks
FROM EXAMMARK AS T1 JOIN STUDENT AS T2 ON T1.Rollno = T2.Rollno
WHERE (Marks>=80) 
--
SELECT T1.Rollno,T2.StuName,T2.Gender,T2.Address,T1.SubID,T1.Marks
FROM EXAMMARK AS T1 JOIN STUDENT AS T2 ON T1.Rollno = T2.Rollno
WHERE (Marks < (SELECT AVG(Marks)
FROM EXAMMARK)) 

SELECT AVG(Marks)
FROM EXAMMARK
