CREATE DATABASE UnitedAir
ON PRIMARY
(NAME=N'UnitedAir',FILENAME=N'D:\UnitedAir.mdf',SIZE=5MB,MAXSIZE=10MB,FILEGROWTH=15%)
LOG ON
(NAME=N'UnitedAir_Log',FILENAME=N'D:\UnitedAir_Log.ldf',SIZE=5MB,MAXSIZE=10MB,FILEGROWTH=15%)
