CREATE DATABASE SELL_MANAGER
ON PRIMARY
(NAME=N'SELL_MANAGE',FILENAME=N'D:\SELL_MANAGE.mdf',SIZE=500MB,MAXSIZE=10GB,FILEGROWTH=50MB)
LOG ON 
(NAME=N'SELL_MANAGE_Log',FILENAME=N'D:\SELL_MANAGE_Log.ldf',SIZE=100MB,MAXSIZE=1GB,FILEGROWTH=10MB)