INSERT INTO STUDENT VALUES('SV01','Lam Ngoc Dong Nhi','female','So 2 Hai Ba Trung, TPCT')
INSERT INTO STUDENT VALUES('SV02','Pham Dan Truong','male','Long Xuyen, An Giang')
INSERT INTO STUDENT VALUES('SV03','Ngo Kien Huy','male','Cai Be, Tien Giang')
INSERT INTO STUDENT VALUES('SV04','Ho Ngoc Ha','female','20/5 Tran Hung Dao, TPCT')

INSERT INTO SUBJECT VALUES('EPC','Logic Building with C',30,30)
INSERT INTO SUBJECT VALUES('HDJ','HTML, DHTML, JAVASCRIPT',25,30)
INSERT INTO SUBJECT VALUES('DWMX','DREAMWEAVER MX',20,22)
INSERT INTO SUBJECT VALUES('SQL','SQL SERVER 2015',20,30)

INSERT INTO EXAMMARK VALUES('SV01','EPC',1,40)
INSERT INTO EXAMMARK VALUES('SV01','HDJ',1,50)
INSERT INTO EXAMMARK VALUES('SV02','HDJ',1,20)
INSERT INTO EXAMMARK VALUES('SV02','HDJ',2,70)
INSERT INTO EXAMMARK VALUES('SV03','EPC',1,30)
INSERT INTO EXAMMARK VALUES('SV03','EPC',2,90)
INSERT INTO EXAMMARK VALUES('SV04','SQL',1,80)
--
