insert into STUDENT values (1,'Tran Van A', 'male', 'TPCT')
insert into STUDENT values (2,'Tran Van B', 'male', 'Hau Giang')
insert into STUDENT values (3,'Tran Van C', 'male', 'Vinh Long')
insert into STUDENT values (4,'Tran Thi D', 'male', 'TPCT')
insert into STUDENT values (5,'Tran Thi E', 'male', 'Vinh Long')
insert into STUDENT values (6,'Tran Van F', 'male', 'Tra Vinh')
--
insert into SUBJECT values(1, 'HDJ', 10,5)
insert into SUBJECT values(2, 'EPC', 12,10)
insert into SUBJECT values(3, 'SubName 3', 15,15)
insert into SUBJECT values(4, 'SubName 4', 10,5)
insert into SUBJECT values(5, 'SubName 5', 12,9)
insert into SUBJECT values(6, 'SubName 6', 5,5)
insert into SUBJECT values(7, 'SubName 7', 6,5)
--
insert into [EXAMMARK]  values (1,1,1,40)
insert into [EXAMMARK]  values (2,1,1,55)
insert into [EXAMMARK]  values (3,1,1,60)
insert into [EXAMMARK]  values (4,1,1,84)
insert into [EXAMMARK]  values (5,1,1,35)
insert into [EXAMMARK]  values (6,1,1,53)
insert into [EXAMMARK]  values (1,2,2,60)
insert into [EXAMMARK]  values (2,2,2,55)
insert into [EXAMMARK]  values (3,2,2,60)
insert into [EXAMMARK]  values (4,2,2,84)
insert into [EXAMMARK]  values (5,2,2,41)
insert into [EXAMMARK]  values (6,2,2,53)
--
