USE QLCT
-- 1
SELECT CT.MSCT, CT.TENTHAU, SUM(C.KINHPHI) TONG_KINHPHI
FROM CONGTRINH C
	JOIN CHUTHAU CT ON CT.MSCT = C.MSCT
GROUP BY CT.MSCT, CT.TENTHAU

--2
SELECT KTS.MSKTS , KTS.HOTENKTS, SUM(TK.THULAO) TONG_THULAO
FROM KIENTRUCSU KTS
	JOIN THIETKE TK ON TK.MSKTS = KTS.MSKTS
GROUP BY KTS.MSKTS , KTS.HOTENKTS
HAVING SUM(TK.THULAO) > 25

--3
WITH KTS AS
(
	SELECT KTS.MSKTS , KTS.HOTENKTS, SUM(TK.THULAO) TONG_THULAO
	FROM KIENTRUCSU KTS
		JOIN THIETKE TK ON TK.MSKTS = KTS.MSKTS
	GROUP BY KTS.MSKTS , KTS.HOTENKTS
	HAVING SUM(TK.THULAO) > 25
)
SELECT COUNT(MSKTS) SOLUONG_KTS FROM KTS

--4
SELECT TG.STTCT, CTR.TENCT, COUNT(TG.MSCN) SOLUONG_CN
FROM THAMGIA TG
	JOIN CONGTRINH CTR ON CTR.STTCT = TG.STTCT
GROUP BY TG.STTCT, CTR.TENCT
GO

--5
WITH SLCN AS
(
	SELECT CTR.TENCT, CTR.DIACHICT, COUNT(TG.MSCN) SL_CN
	FROM CONGTRINH CTR
		JOIN THAMGIA TG ON TG.STTCT = CTR.STTCT
	GROUP BY CTR.TENCT, CTR.DIACHICT
)
SELECT TENCT, DIACHICT 
FROM SLCN
WHERE SL_CN = (SELECT MAX(SL_CN) FROM SLCN)

--6
SELECT TINHTHANH, AVG(KINHPHI) TB_KINHPHI
FROM CONGTRINH
GROUP BY TINHTHANH
GO

--7
WITH TONGSN AS
(
	SELECT CN.MSCN, CN.HOTENCN, SUM(SONGAY) SONGAY
	FROM CONGNHAN CN
		JOIN THAMGIA TG ON TG.MSCN = CN.MSCN
	GROUP BY CN.MSCN, CN.HOTENCN
)
SELECT HOTENCN FROM TONGSN
WHERE SONGAY > (SELECT SONGAY FROM TONGSN WHERE HOTENCN = 'Nguyen Hong Van')

--8
SELECT TINHTHANH, CHUTHAU.MSCT, CHUTHAU.TENTHAU, COUNT(STTCT) SL_CONGTRINH
FROM CONGTRINH
	JOIN CHUTHAU ON CHUTHAU.MSCT = CONGTRINH.MSCT
GROUP BY TINHTHANH, CHUTHAU.MSCT, CHUTHAU.TENTHAU
GO

--9
DECLARE @SOCT INT = (SELECT COUNT(MSCT) FROM CONGTRINH)
SELECT TG.MSCN, CN.HOTENCN
FROM THAMGIA TG
	JOIN CONGNHAN CN ON CN.MSCN = TG.MSCN
GROUP BY TG.MSCN , CN.HOTENCN
HAVING COUNT(STTCT) = @SOCT

--10
WITH TEMP AS
(
	SELECT DISTINCT TG.STTCT
	FROM THAMGIA TG
		JOIN CONGNHAN CN ON CN.MSCN = TG.MSCN
	WHERE CN.HOTENCN = 'Nguyen Thi Suu' OR CN.HOTENCN = 'Le Manh Quoc'
)
SELECT CTR.STTCT, TENCT
FROM CONGTRINH CTR 
	JOIN TEMP ON TEMP.STTCT = CTR.STTCT