CREATE DATABASE HANGKHONG

USE HANGKHONG
-- Create table Employees
DROP TABLE IF EXISTS [dbo].CHUYENBAY 
CREATE TABLE CHUYENBAY 
(
	MaCB char(5),
	GaDi varchar(50),
	GaDen varchar(50),
	DoDai int,
	GioDi time,
	GioDen time,
	ChiPhi int,
	CONSTRAINT PK_MaCB
    PRIMARY KEY(MaCB)
)
DROP TABLE IF EXISTS [dbo].MAYBAY
CREATE TABLE MAYBAY(
	MaMB int,
	Hieu varchar(50),
	TamBay int
	CONSTRAINT PK_MaMB
    PRIMARY KEY(MaMB)
)
DROP TABLE IF EXISTS [dbo].NHANVIEN
CREATE TABLE NHANVIEN(
 MaNV char(9),
 Ten varchar(50),
 Luong int
 CONSTRAINT PK_MaNV PRIMARY KEY(MaNV)
)
DROP TABLE IF EXISTS [dbo].CHUNGNHAN
CREATE TABLE CHUNGNHAN(
	MaNV char(9),
	MaMB int,
	CONSTRAINT PK_MaNV_MaMB PRIMARY KEY(MaNV,MaMB),
	CONSTRAINT FK_CHUNGNHAN_NHANVIEN FOREIGN KEY(MaNV) REFERENCES dbo.NHANVIEN(MaNV),
	CONSTRAINT FK_CHUNGNHAN_MAYBAY FOREIGN KEY(MaMB) REFERENCES dbo.MAYBAY(MaMB)
)